# Generated by Django 4.2 on 2024-04-21 07:19

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('employment_at', models.DateField()),
                ('position', models.CharField(choices=[('position_1', 'position_1'), ('position_2', 'position_2'), ('position_3', 'position_3'), ('position_4', 'position_4'), ('position_5', 'position_5'), ('position_6', 'position_6'), ('position_7', 'position_7'), ('position_8', 'position_8')], max_length=20)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('boss', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workmates', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
